### ISSUE TITLE
"Open" of previously saved list from Mac/old firefox panicked Windows 7 quantum

### ISSUE THREAD

**Issue by tanstaaf1** [moritz-h/urls-list#17] opened 2017-12-22 02:32 UTC
Hi,   Before I complain I want to thank you:   I had been running FF52 for ages as I wasn't willing to lose all my grouped tabs.  

With your utility on the mac I saved a plaintext list of all my tabs and emailed them to my windows 7 machine to try loading them into quantum.  I did that by first viewing them in notepad.  Then I deleted a few lines or urls I knew I didn't want and cut and pasted the rest.

That is when I got my blue screen of death as a whole bunch of panic messages flooded the system before it crashed.

Although I don't think any of my tabs were corrupted, I would think your utility would make sure they were safe to load...   I rebooted in safe mode. Then rebooted again in normal.  Did a superANTISpyware scan (which found tracking cookies..which I presume were already there but who knows) deleted them.

And then I cut and pasted ONE of my urls from your list to the browser and it came up okay.

So...long story short:  the "Load" command doesn't appear safe but the application running on my mac has apparently saved several hundred urls I didn't want to lose...and now I won't! :-)

Thanks and let me know if you think you find a way to fix the unsafe "load" or need further info.   I'm going to hold off on rating the app for a while.  Mostly I'm just feeling grateful but think you might want to see if anyone else has a similar experience with a memory panic.

**Comment by moritz-h** [comment] 2017-12-23 18:14
This looks like a Firefox issue if it is reproducable. The load function is just a little bit of javascript calling [tabs.create()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create) on the Firefox Webextension API.

But to find where the issue comes from:
- Can you open your URLS on other Computers?
- Does all your URLs Start with http:// or https://? (if not please provide an example)
- How much URLs are you opening (round about)?
- Does this happen if you open the URLs in packs of around only 50 URLs at once?
- Do you have other Firefox extensions installed? If yes can you please retry with temporary disabling other addons?
- Do you have Antivirus Software installed?

**Comment by moritz-h** [comment] 2018-12-31 11:45
Not reproducible for me and no user feedback for >1year. Therefore close this issue.

**Closed by moritz-h** 2018-12-31 11:45 UTC
