### ISSUE TITLE
Visual bugs 

### ISSUE THREAD

**Issue by rayman89** [moritz-h/urls-list#13] opened 2017-11-25 07:27 UTC
I'm on the latest firefox dev version x64 on windows 7 x64

 I noticed is that when a filter is active the buttons at the bottom get duplicated and when you scroll down the list quickly you'll see graphic glitches like duplicated urls black rectangles a ghost url cut in half at the end and more but they all disappear after a few seconds.

![image](https://user-images.githubusercontent.com/5449042/33228388-c3b93554-d17f-11e7-91bc-bba8350297ee.png)

![image](https://user-images.githubusercontent.com/5449042/33228392-cb61e76a-d17f-11e7-9cbd-66cbd5b5b62f.png)

![image](https://user-images.githubusercontent.com/5449042/33228395-ceab6036-d17f-11e7-9760-a1b89c3b2480.png)

**Comment by moritz-h** [comment] 2017-11-25 11:47
I have now also tried on Windows and can reproduce this. But I start thinking that this is a bug in Firefox. The popup is just a small html page, this Addon has nothing to do with the rendering. It seems that the current view is kept as background when the layout changes instead doing a background clearing.

**Comment by moritz-h** [comment] 2017-11-25 11:55
I found a related Firefox bugtracker report: https://bugzilla.mozilla.org/show_bug.cgi?id=1418677

**Comment by rayman89** [comment] 2017-11-25 15:42
I see. If you could comment on there it would be great as It shows as unconfirmed so they havent recognized it as a bug yet.

**Comment by moritz-h** [comment] 2018-12-31 11:36
I don't see this issue anymore on Firefox 64. According to the the discussion in the Firefox bugtracker this seems to be fixed at least with Firefox 62 and later.
Therefore I close this issue here now. Please write feedback if you see this issue again.

**Closed by moritz-h** 2018-12-31 11:36 UTC
