### ISSUE TITLE
[Feature Request] Open in order

### ISSUE THREAD

**Issue by lonix1** [moritz-h/urls-list#27] opened 2019-09-22 07:09 UTC
If I paste a bunch of URLs into the popup and click "Open", they are not opened in order - they are opened in some weird random order.

Please force URLs to open in the order that they are pasted?

**Comment by ElectricStars** [comment] 2020-01-28 19:10
Yes, this is an annoying feature. If I want the same order I had when saved, I need to open a spreadsheet with the urls with a number column and invert the order myself.

**Comment by lonix1** [comment] 2020-01-29 06:13
I'm no longer sure whether this is the case. I'm using another plugin that opens tabs "next to the current one". I think (maybe) those kind of plugins interfere with this one - but I'm not sure.

**Comment by moritz-h** [comment] 2020-01-29 10:25
I cannot reproduce this issue. For me all tabs open in order of the list.
The code calls the tabs.create() function of the Firefox API in order of the list (sidenote: already opened URLs are excluded). I found no documentation about if Firefox guarantees any stability on this process. But at least I can observe that works as intended on my computers.

@lonix1 can you please verify this by temporarily disabling the other plugin?

@ElectricStars do you have any other plugins installed?
Can you otherwise please provide more Information of your Firefox cersion and what operating system are you using?

**Comment by lonix1** [comment] 2020-01-29 16:04
Yes for me its the other extension, when it's disabled then this extension opens links in order. I wish I could use both - is there maybe a "force" option in the API, that ignores overrides by other extensions?

@ElectricStars how about you?

**Comment by moritz-h** [comment] 2022-07-23 15:43
Not reproducible for me. The only feedback so far indicates a problem with an other plugin. Therefore, closing.

**Closed by moritz-h** 2022-07-23 15:43 UTC
