### ISSUE TITLE
[Feature Request] Add ability to handle file URLs

### ISSUE THREAD

**Issue by GCatLC** [moritz-h/urls-list#25] opened 2019-02-11 16:59 UTC
...such as file:///c:/myfile.jpg

**Comment by mnba** [comment] 2019-02-12 02:04
I would suggest you use my Save Tab URL+Titles extension
https://addons.mozilla.org/en-US/firefox/addon/save-tab-urls/
which is still mostly fork of this one, but have such hitches removed, file:// protocol supported too
And be aware it takes page Titles too. Title is useful when link dies: you still can find the info or at least related

**Comment by GCatLC** [comment] 2019-02-12 03:22
Thanks much. I installed this extension and tried it. It did not work.
(Example: file:///d:/System/AndroidHome.html)  on a Windows system. 
 
Is there some other Firefox setting that could be affecting it? 

  _____

**Comment by moritz-h** [comment] 2019-02-12 10:58
@GCatLC are you talking about seeing the file urls in the list or about opening the URLs?

Seeing the file URLs in the list works for me, but i can reproduce that they could not be opened.
Can you please confirm if this is what you mean?

I could find this in the Firefox docs:
> For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail:
> chrome: URLs
> javascript: URLs
> data: URLs
> file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)
> privileged about: URLs (for example, about:config, about:addons, about:debugging). Non-privileged URLs (e.g., about:blank) are allowed.
> The New Tab page (about:newtab) can be opened if no value for URL is provided.
> -- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create

So it seems that it is not possible for plugins to open `file://` URLs. I must see if it is possible to workaround this somehow or at least show a warning as feedback that Firefox blocks this.

@mnba It would be nice if you join the technical discussion and not use the issue tracker as advertising platform, especially as your fork seems to have the same issue.

**Comment by GCatLC** [comment] 2019-02-12 14:42
I am talking about the extension not being able to open local files. (I so
see them in the extension once they are opened.)
 
So it sounds like it's not allowed for security reasons. I guess that makes
sense. Thanks for investigating. 
 
And thanks for the nice extension!  
 
  _____

**Comment by mnba** [comment] 2019-02-15 23:06
@moritz-h issue tracker is for solving problems of users, not only specific definition of technical issues, and that is exactly what I tried to do. Your previous version of code didn't support protocols except of explicitly defined limited set, So back ago I removed this limitation, glad to see, you do that too.
And I am was not sure this time you will not ignore your extension users as you did before, that is why I suggested a solution.

**Comment by ElectricStars** [comment] 2020-01-28 19:16
This is a 2nd separate request for the same feature. The extension can save urls to a file. It should be able to open the same file, or other saved urls text file, with an open file dialog box. The extension should also open the tabs in order they were saved, not in reverse order as is the current function of the extension.
Thanks.

**Comment by moritz-h** [comment] 2020-01-29 10:38
This issue is about opening `file://` urls withtin the list. Unfortunately this is not possible, because Firefox does not allow this to plugins for security reasons. Therefore I need to close this issue as cannot be fixed.

@ElectricStars reading a saved list file with an open file dialog could be done, but that is independent from this issue. Can you please open a new issue with this feature request to keep that issue separately?

**Closed by moritz-h** 2020-01-29 10:38 UTC
